version: "3"
services:
#  generate-config:
#    container_name: ${COMPOSE_PROJECT_NAME}-generate-config
#    image: ${GITEA_ACT_RUNNER_IMAGE}:${GITEA_ACT_RUNNER_TAG}
#    entrypoint: ["/bin/sh", "-c"]
#    command: ["act_runner generate-config > /data/config.yaml"]
#    volumes:
#      - data:/data
#    stdin_open: true
#    tty: true

  runner:
    container_name: ${COMPOSE_PROJECT_NAME}-runner
    image: ${GITEA_ACT_RUNNER_IMAGE}:${GITEA_ACT_RUNNER_TAG}
    privileged: true
    restart: always
    command: act_runner generate-config > /data/config.yaml
    environment:
#      CONFIG_FILE: /data/config.yaml
      DOCKER_HOST: unix:///run/user/1000/docker.sock
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${GITEA_RUNNER_NAME}
    volumes:
      - cache:/tmp/buildx-cache
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  cache:
  config:
  data:

networks:
  default:
    name: ${NETWORK}
    external: true
