services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: ${MYSQL_IMAGE}:${MYSQL_TAG}
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  gitea:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: ${GITEA_IMAGE}:${GITEA_TAG}
    restart: always
    depends_on:
      - db
    ports:
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - data:/var/lib/gitea
      - config:/etc/gitea
      - custom:/data/gitea/custom
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: ${COMPOSE_PROJECT_NAME}-mysql:3306
      GITEA__database__NAME: ${MYSQL_DATABASE}
      GITEA__database__USER: ${MYSQL_USER}
      GITEA__database__PASSWD: ${MYSQL_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=myresolver"
      - "traefik.http.services.gitea.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.gitea.service=gitea"

volumes:
  db:
  data:
  config:
  custom:

networks:
  default:
    name: ${NETWORK}
    external: true
