version: '3'

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    hostname: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    restart: always
    environment:
      TIMEZONE: ${TIMEZONE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DB_EXTENSION: ${DB_EXTENSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    hostname: ${COMPOSE_PROJECT_NAME}-server
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    restart: always
    environment:
      TZ: ${TIMEZONE}
      VIRTUAL_PORT: 8000
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      VIRTUAL_HOST: ${URL},www.${URL}
      LETSENCRYPT_HOST: ${URL},www.${URL}
    volumes:
      - "gnuhealth-data:/var/lib/trytond/db"      
    command: "bash -c '(until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-postgres/${POSTGRES_PORT:-5432}; do sleep 0.5; done) 2>/dev/null; \
      echo \"${PASSWORD:-admin}\" > /tmp/.passwd; \
      TRYTONPASSFILE=/tmp/.passwd /entrypoint.sh trytond-admin -d \"${DB_NAME}\" --all --email \"${EMAIL}\" -l \"${GNUHEALTH_LANGUAGE}\" -vv; \
      echo \"Instalando módulo country...\"; \
      /entrypoint.sh trytond-admin -d \"${DB_NAME}\" -u country --activate-dependencies -vv; \
      echo \"Módulo country instalado correctamente...\"; sleep 5; \
      echo \"Importando datos de países en la base de datos: ${DB_NAME} ...\"; \
      /entrypoint.sh trytond_import_countries -d \"${DB_NAME}\"; \
      echo \"Paises importados correctamente en la base de datos: ${DB_NAME} ...\"; \
      echo \"Instalando módulo currency...\"; \
      /entrypoint.sh trytond-admin -d \"${DB_NAME}\" -u currency --activate-dependencies -vv; \
      echo \"Módulo currency instalado correctamente...\"; sleep 5; \
      echo \"Importando datos de monedas en la base de datos: ${DB_NAME} ...\"; \
      /entrypoint.sh trytond_import_currencies -d \"${DB_NAME}\"; \
      echo \"Monedas importadas correctamente en la base de datos: ${DB_NAME} ...\"; \
      if command -v uwsgi &>/dev/null; then uwsgi --ini /etc/uwsgi.conf; else gunicorn --config=/etc/gunicorn.conf.py; fi'"
    depends_on:
      - postgres

  gnuhealth-cron:
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS} 
    volumes:
      - gnuhealth-data:/var/lib/trytond/db
    command: "bash -c '(until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-server/8000; do sleep 0.5; done) 2>/dev/null; trytond-cron -d \"${DB_NAME}\"'"
    depends_on:
      - postgres
      - server

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    restart: always
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025

volumes:
  postgres-data:
  gnuhealth-data:

networks:
  default:
    name: ${NETWORK}
    external: true
