version: '3'

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    hostname: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    restart: always
    environment:
      TIMEZONE: ${TIMEZONE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DB_EXTENSION: ${DB_EXTENSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    hostname: ${COMPOSE_PROJECT_NAME}-server
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    restart: always
    environment:
      TZ: ${TIMEZONE}
      VIRTUAL_PORT: 8000
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      VIRTUAL_HOST: ${URL},www.${URL}
      LETSENCRYPT_HOST: ${URL},www.${URL}
    volumes:
      - "gnuhealth-data:/var/lib/trytond/db"
    depends_on:
      - postgres

  gnuhealth-cron:
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS} 
    volumes:
      - gnuhealth-data:/var/lib/trytond/db
    entrypoint: ["/entrypoint_cron.sh"]
    depends_on:
      - postgres
      - server

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    restart: always
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025

volumes:
  postgres-data:
  gnuhealth-data:

networks:
  default:
    name: ${NETWORK}
    external: true
