version: "3.6"
services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    hostname: ${COMPOSE_PROJECT_NAME}-postgres
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    environment:
      TIMEZONE: ${TIMEZONE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SUPERUSER_PASS: ${SUPERUSER_PASS}
      DB_EXTENSION: ${DB_EXTENSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  server:
    container_name: ${COMPOSE_PROJECT_NAME}-server
    hostname: ${COMPOSE_PROJECT_NAME}-server
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    environment:
      DB_PASSWORD: ${DB_PASS} 
    ports:
      - "8000:8000"
    volumes:
      - "gnuhealth-data:/var/lib/trytond/db"
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-postgres/5432; do sleep 0.5; done) 2>/dev/null
        echo "${PASSWORD:-admin}" > /tmp/.passwd
        TRYTONPASSFILE=/tmp/.passwd /entrypoint.sh trytond-admin -d "${DB_NAME:-tryton}" --all -l ${GNUHEALTH_LANGUAGE} --email "${EMAIL:-}" -vv
        if command -v uwsgi &>/dev/null; then uwsgi --ini /etc/uwsgi.conf; else gunicorn --config=/etc/gunicorn.conf.py; fi 
    depends_on:
      - postgres

  gnuhealth-cron:
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    image: ${GNUHEALTH_IMAGE}:${GNUHEALTH_TAG}
    environment:
      DB_PASSWORD: ${DB_PASS} 
    volumes:
      - gnuhealth-data:/var/lib/trytond/db
    command:
      - /bin/bash
      - -c
      - |
        (until echo > /dev/tcp/${COMPOSE_PROJECT_NAME}-app/8000; do sleep 0.5; done) 2>/dev/null
        trytond-cron -d "${DB_NAME}"
    depends_on:
      - postgres
      - gnuhealth-app
    restart: always

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}-mailhog
    image: ${MAILHOG_IMAGE}:${MAILHOG_TAG}
    restart: always
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025

volumes:
  postgres-data:
  gnuhealth-data:
